# -*- coding: utf-8 -*-
"""prelecture_notebook_answer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k13dHTQW1Hqf0Eq_Qy8ovCzG9lL69gqz

# Practice Questions Solutions

## 1.7. Practice Questions

(1-1) Write a program that outputs a string of your choice.
"""

print("Hello World!")

"""Example: When x="Hello" and y="Mr. Matsuo", print x+y."""

x = "Hello"
y = "Mr. Matsuo"
print(x + y)

"""(1-2) Please write one or more programs performing any operations of your choice using arithmetic operators (+, -, *, /, %, **, //)."""

a = 1
b = 2

# addition
print("Addition: ", a + b)

# subtraction
print("Subtraction: ", a - b)

# multiplication
print("Multiplication: ", a * b)

# division
print("Division: ", a / b)

# integer division
print("Integer division: ", a // b)

# remainder
print("Remainder: ", a % b)

# Exponential
print("Exponential: ", a ** 2)

"""(1-3) Let's assume that an integer is stored in the variable `x`. Create a program that will display (print) 0 if `x` is even, and 1 if `x` is odd."""

x = 1 # Input example

print(x % 2)

"""(1-4) Create a program to calculate BMI from height and weight. BMI = weight(kg) / (height(m))^2"""

# Input example
weight = 50 # kg
height = 165 # cm

bmi = weight / ((height / 100) ** 2)
print(bmi)

"""## 2.5 Practice Questions

(2-1) Write a list that includes all prime numbers less than 10.
"""

primes_list = [2, 3, 5, 7]
print(primes_list)

"""(2-2) Write a tuple that includes all prime numbers less than 10.

"""

primes_tuple = (2, 3, 5, 7)
print(primes_tuple)

"""(2-3) Write a dictionary whose key is the string `'name'` and whose value is a string containing your own name."""

name = {'name': "Taro"}
print(name)

"""## 3.3. Practice Questions

(3-1) Write a program using the `if` statement.
"""

a = 1
if a % 2 == 0:
    print("Even")
else:
    print("Odd")

"""(3-2) Write a program of your choice using a `for` loop."""

sample_list = [1, 2, 3, 4, 5]

for i in sample_list:
    print(i % 2)

"""(3-3) Let's assume that a variable `x` contains a list of integers with a length of 1 or more. Create a program that returns the largest element in `x`. Achieve this without using functions like `max()`, and instead use loops (repetition with `for` statement)."""

x = [1, 2, 3]  # Input example

largest = x[0]
for i in x:
    if i > largest:
        largest = i
print(largest)

"""## 4.2. Practice Questions

(4-1) Define a function `f` that takes a string `x` with a length of 1 or more as an argument and returns the last character of `x`.
"""

x = 'python'

def last_char(x):
    return x[-1]

last_char(x)

"""(4-2) Define a function `f` that takes a dictionary as an argument `x` and returns the number of keys stored in `x`."""

x = {"a": 1, "b": 2, "c": 3, 'd':4, 'e':5}

def num_keys(x):
    return len(x.keys())

num_keys(x)

"""(4-3)
Define a function `f` that takes a list as an argument `x` and returns a list of elements of `x` in reverse order. However, achieve this without using functions like `reversed`, but using loops or list slicing.
"""

x = [3, 9, 7, 1, 0]

def f(x):
    y = []
    for i in range(len(x)):
        y.append(x[-i-1])
    return y

f(x)

"""(4-4) The following function was intended to display "I am X years old." However, as it is, it results in an error. Please modify the function below. The argument for the function, `age`, is expected to be an integer. Assign the string you want to display to `msg`, store it in a dictionary. Then, print the value from the dictionary by specifying its key."""

def print_my_age(age):
    msg = 'My age is ' + str(age) + ' years old.'
    msg_dict = {'msg': msg}
    print(msg_dict['msg'])

print_my_age(18)

